---
title: "Appartments_reload"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pacman)
p_load(tidyverse, rvest, devtools, RSelenium)

raw <- read_csv("raw.csv")
```


Apartment scraping 2.0

# list of links
```{r}
# load complete html doc of the site
html_link <- read_html("190227_lejebolig.htm")

# get all links
link_list <- html_link %>%
  html_nodes("a") %>%
  html_attr("href")

link_list_chr <- unlist(link_list)

### cleaning list of url links
link_list_df <- as.data.frame(link_list_chr) %>%
  filter(!str_detect(link_list_chr, "google") &
         !str_detect(link_list_chr, "Hunter") &
         !str_detect(link_list_chr, "min-konto") &
         !str_detect(link_list_chr, "Scripts") &
         !str_detect(link_list_chr, "scripts") &
         !str_detect(link_list_chr, "Content") &
         !str_detect(link_list_chr, "content") &
         !str_detect(link_list_chr, "facebook") &
         !str_detect(link_list_chr, "artikler") &
         !str_detect(link_list_chr, "/lejebolig/aarhus")) %>%
  mutate(link_list_chr = str_remove(link_list_chr, "view-source:"))

View(link_list_df)

clean_link_list <- as.character(link_list_df[17:2234,1])
clean_link_list_unique <- unique(clean_link_list)
```

# scraping loop
```{r}
scraper <- function(link){

  timeout = sample(5, 1) + exp(rnorm(1))
  
  scrape <- read_html(link)
  
  Sys.sleep(timeout)
  
  # SUMMARY TILES SCRAPE
  basic_data <- scrape %>%
    html_nodes(".col-xs-4") %>%
    html_text()
  
  basic_data.df <- as.data.frame(basic_data)
  basic_data.df <- t(basic_data.df)
  
  basic_data.df <- basic_data.df %>%
    str_replace_all(pattern = "\n", replacement = " ") %>%
    str_replace_all(pattern = "\r", replacement = " ") %>%
    str_replace_all(pattern = "\t", replacement = " ") %>%
    str_trim(side = "both")
  
  basic_data.df <- as.data.frame(t(basic_data.df))
  
  Sys.sleep(timeout)
  
  
  # WHOLE TEXT SCRAPE
  all_text <- scrape %>%
    html_nodes(".lease-text") %>%
    html_text()
  
  all_text.df <- as.data.frame(all_text[1])
  
  all_text.df <- t(all_text.df)
  
  all_text.df <- all_text.df %>%
    str_replace_all(pattern = "\n", replacement = " ") %>%
    str_replace_all(pattern = "\r", replacement = " ") %>%
    str_replace_all(pattern = "\t", replacement = " ") %>%
    str_trim(side = "both")
  
  
  # JOIN DATA
  combo <- cbind.data.frame(basic_data.df, all_text.df)
  return(combo)
}
```

# running the scrape
```{r}
raw <- map_df(clean_link_list_unique, scraper)
```

# cleaning the scrape
```{r}
var_extract <- function(data) {
  
  df_clean <- data  %>%
    # BAISC DATA
    mutate(rent_b = str_remove_all(V1, "\\."),
           rent_b = str_remove(rent_b, " kr/md"),
           rent_b = str_extract(rent_b, "(\\d)+"),
           length = V2,
           type_b = V3,
           loc_b = V4,
           sqm_b = str_extract(V5, "(\\d)+"),
           rooms_b = str_extract(V6, "(\\d)+")
           ) %>%
    select(-(V1:V6)) %>%
    # ALL DATA
    separate(all_text.df, 
             into = c("type", "street", "loc", "rest"), 
             sep = ",") %>%
    mutate(type = str_trim(type, side = "both"),
           street = str_trim(street, side = "both"),
           loc = str_trim(loc, side = "both")) %>%
    separate(loc, into = c("post_nr", "loc"), sep = " ") %>%
    mutate(etage = as.character(str_extract_all(rest, "etage: ......")),
           etage = tolower(etage),
           etage = case_when(str_detect(etage, "stuen|st") ~ "0",
                             TRUE ~ str_extract(etage, "[1-9]")),
           # rooms
           rooms = as.character(str_extract_all(rest, "Antal værelser: [1-9]")),
           rooms = str_extract(rooms, "[1-9]"),
           # m2
           sqm = as.character(str_extract_all(rest, "Antal m2: [1-9]*")),
           sqm = str_remove(sqm, "Antal m2: "),
           # rent
           rent = str_extract(rest, "Husleje..........."),
           rent = str_remove_all(rent, "\\."),
           rent = str_extract(rent, "(\\d)+"),
           # indskud
           indskud = str_extract(rest, "Indskud:.........."),
           indskud = str_remove_all(indskud, "\\."),
           indskud = str_extract(indskud, "(\\d)+"),
           # deposit
           deposit = str_extract(rest, "Depositum:.........."),
           deposit = str_remove_all(deposit, "\\."),
           deposit = str_extract(deposit, "(\\d)+"),
           # advance_rent
           advance_rent = str_extract(rest, "Forudbetalt leje:.........."),
           advance_rent = str_remove_all(advance_rent, "\\."),
           advance_rent = str_extract(advance_rent, "(\\d)+"),
           # ac_usage
           ac_usage = str_extract(rest, "A/C-forbrug:....."),
           ac_usage = str_remove_all(ac_usage, "\\."),
           ac_usage = str_extract(ac_usage, "(\\d)+"),
           # avaiable 18 char
           avaiable = str_extract(rest, "Ledig:.................."),
           avaiable = str_remove(avaiable, "Ledig: "),
           avaiable = str_trim(avaiable, side = "both"),
           # published 18 char
           published = str_extract(rest, "Indrykket:.................."),
           published = str_remove(published, "Indrykket: "),
           published = str_trim(published, side = "both"),
           # balcony
           balcony = str_detect(rest, "Altan/terasse"),
           # lift
           lift = str_detect(rest, "Elevator"),
           # ID
           ID = str_extract(rest, "Sagsnummer:........"),
           ID = str_remove(ID, "Sagsnummer: "),
           ID = str_trim(ID, side = "both"),
           # REST
           rest = str_trim(rest, side = "both"),
           rest = str_replace_all(rest, "  ", " ")
    ) %>%
    select(rest, 
           # comparing the two scrapes
           rent_b, rent, sqm_b, sqm, rooms_b, rooms, type_b, type, loc_b, loc, 
           # primary extracted variables
           street, post_nr, etage, length, indskud, deposit, advance_rent,
           # secondary extracted varialbes
           ac_usage, avaiable, published, balcony, lift, ID)
    
  return(df_clean)
  
}
```

# run cleaning
```{r}
cl <- var_extract(raw)
glimpse(cl)
```

# validate clenliness
```{r}
cl2 <- cl %>%
  mutate(street = ifelse(str_detect(street, "Antal værelser"), NA, street),
         street = ifelse(str_detect(street, loc_b), NA, street)) %>%
  select(-rent, -sqm, -rooms, -type, -loc) %>%
  # description in lower case
  mutate(rest = tolower(rest)) %>%
  # str detection in description
  mutate(hyg = ifelse(str_detect(rest, "hygge"), 1, 0),
         dej = ifelse(str_detect(rest, "dejligt"), 1, 0),
         social = ifelse(str_detect(rest, "soc"), 1, 0),
         desc = ifelse(is.na(rest), 0, 1)
         )


```

